package generatedAssertions.customAssertions;

import org.springframework.samples.petclinic.model.Intervention;

/**
 * {@link Intervention} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractInterventionAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class InterventionAssert extends AbstractInterventionAssert<InterventionAssert, Intervention> {

  /**
   * Creates a new <code>{@link InterventionAssert}</code> to make assertions on actual Intervention.
   * @param actual the Intervention we want to make assertions on.
   */
  public InterventionAssert(Intervention actual) {
    super(actual, InterventionAssert.class);
  }

  /**
   * An entry point for InterventionAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myIntervention)</code> and get specific assertion with code completion.
   * @param actual the Intervention we want to make assertions on.
   * @return a new <code>{@link InterventionAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static InterventionAssert assertThat(Intervention actual) {
    return new InterventionAssert(actual);
  }
}
