package generatedAssertions.customAssertions;

import org.springframework.samples.petclinic.model.MedicalRecord;

/**
 * {@link MedicalRecord} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractMedicalRecordAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class MedicalRecordAssert extends AbstractMedicalRecordAssert<MedicalRecordAssert, MedicalRecord> {

  /**
   * Creates a new <code>{@link MedicalRecordAssert}</code> to make assertions on actual MedicalRecord.
   * @param actual the MedicalRecord we want to make assertions on.
   */
  public MedicalRecordAssert(MedicalRecord actual) {
    super(actual, MedicalRecordAssert.class);
  }

  /**
   * An entry point for MedicalRecordAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myMedicalRecord)</code> and get specific assertion with code completion.
   * @param actual the MedicalRecord we want to make assertions on.
   * @return a new <code>{@link MedicalRecordAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static MedicalRecordAssert assertThat(MedicalRecord actual) {
    return new MedicalRecordAssert(actual);
  }
}
