
package generatedAssertions.customAssertions;

import org.springframework.samples.petclinic.model.Medicine;

/**
 * {@link Medicine} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractMedicineAssert} instead.
 */
@javax.annotation.Generated(value = "assertj-assertions-generator")
public class MedicineAssert extends AbstractMedicineAssert<MedicineAssert, Medicine> {

	/**
	 * Creates a new <code>{@link MedicineAssert}</code> to make assertions on actual Medicine.
	 * 
	 * @param actual
	 *            the Medicine we want to make assertions on.
	 */
	public MedicineAssert(final Medicine actual) {
		super(actual, MedicineAssert.class);
	}

	/**
	 * An entry point for MedicineAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
	 * With a static import, one can write directly: <code>assertThat(myMedicine)</code> and get specific assertion with code completion.
	 * 
	 * @param actual
	 *            the Medicine we want to make assertions on.
	 * @return a new <code>{@link MedicineAssert}</code>
	 */
	@org.assertj.core.util.CheckReturnValue
	public static MedicineAssert assertThat(final Medicine actual) {
		return new MedicineAssert(actual);
	}
}
