
package generatedAssertions.customAssertions;

import org.springframework.samples.petclinic.model.Owner;

/**
 * {@link Owner} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractOwnerAssert} instead.
 */
@javax.annotation.Generated(value = "assertj-assertions-generator")
public class OwnerAssert extends AbstractOwnerAssert<OwnerAssert, Owner> {

	/**
	 * Creates a new <code>{@link OwnerAssert}</code> to make assertions on actual Owner.
	 *
	 * @param actual
	 *            the Owner we want to make assertions on.
	 */
	public OwnerAssert(final Owner actual) {
		super(actual, OwnerAssert.class);
	}

	/**
	 * An entry point for OwnerAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
	 * With a static import, one can write directly: <code>assertThat(myOwner)</code> and get specific assertion with code completion.
	 *
	 * @param actual
	 *            the Owner we want to make assertions on.
	 * @return a new <code>{@link OwnerAssert}</code>
	 */
	@org.assertj.core.util.CheckReturnValue
	public static OwnerAssert assertThat(final Owner actual) {
		return new OwnerAssert(actual);
	}
}
