package generatedAssertions.customAssertions;

import org.springframework.samples.petclinic.model.Prescription;

/**
 * {@link Prescription} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractPrescriptionAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class PrescriptionAssert extends AbstractPrescriptionAssert<PrescriptionAssert, Prescription> {

  /**
   * Creates a new <code>{@link PrescriptionAssert}</code> to make assertions on actual Prescription.
   * @param actual the Prescription we want to make assertions on.
   */
  public PrescriptionAssert(Prescription actual) {
    super(actual, PrescriptionAssert.class);
  }

  /**
   * An entry point for PrescriptionAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myPrescription)</code> and get specific assertion with code completion.
   * @param actual the Prescription we want to make assertions on.
   * @return a new <code>{@link PrescriptionAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static PrescriptionAssert assertThat(Prescription actual) {
    return new PrescriptionAssert(actual);
  }
}
