package generatedAssertions.customAssertions;

import org.springframework.samples.petclinic.model.Rehab;

/**
 * {@link Rehab} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractRehabAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class RehabAssert extends AbstractRehabAssert<RehabAssert, Rehab> {

  /**
   * Creates a new <code>{@link RehabAssert}</code> to make assertions on actual Rehab.
   * @param actual the Rehab we want to make assertions on.
   */
  public RehabAssert(Rehab actual) {
    super(actual, RehabAssert.class);
  }

  /**
   * An entry point for RehabAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myRehab)</code> and get specific assertion with code completion.
   * @param actual the Rehab we want to make assertions on.
   * @return a new <code>{@link RehabAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static RehabAssert assertThat(Rehab actual) {
    return new RehabAssert(actual);
  }
}
