package generatedAssertions.customAssertions;

import org.springframework.samples.petclinic.model.Trainer;

/**
 * {@link Trainer} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractTrainerAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class TrainerAssert extends AbstractTrainerAssert<TrainerAssert, Trainer> {

  /**
   * Creates a new <code>{@link TrainerAssert}</code> to make assertions on actual Trainer.
   * @param actual the Trainer we want to make assertions on.
   */
  public TrainerAssert(Trainer actual) {
    super(actual, TrainerAssert.class);
  }

  /**
   * An entry point for TrainerAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myTrainer)</code> and get specific assertion with code completion.
   * @param actual the Trainer we want to make assertions on.
   * @return a new <code>{@link TrainerAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static TrainerAssert assertThat(Trainer actual) {
    return new TrainerAssert(actual);
  }
}
