
package generatedAssertions.customAssertions;

import org.springframework.samples.petclinic.model.Vet;

/**
 * {@link Vet} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractVetAssert} instead.
 */
@javax.annotation.Generated(value = "assertj-assertions-generator")
public class VetAssert extends AbstractVetAssert<VetAssert, Vet> {

	/**
	 * Creates a new <code>{@link VetAssert}</code> to make assertions on actual Vet.
	 * 
	 * @param actual
	 *            the Vet we want to make assertions on.
	 */
	public VetAssert(final Vet actual) {
		super(actual, VetAssert.class);
	}

	/**
	 * An entry point for VetAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
	 * With a static import, one can write directly: <code>assertThat(myVet)</code> and get specific assertion with code completion.
	 * 
	 * @param actual
	 *            the Vet we want to make assertions on.
	 * @return a new <code>{@link VetAssert}</code>
	 */
	@org.assertj.core.util.CheckReturnValue
	public static VetAssert assertThat(final Vet actual) {
		return new VetAssert(actual);
	}
}
